### ISSUE TITLE
Suggestion to slightly modify Salmon command

### ISSUE THREAD

**Issue by rob-p** [ngs-docs/2015-nov-adv-rna#1]
I'm starting to work through these materials now; they look good!  One suggestion I have is to modify the Salmon command being used from:

```
salmon quant -i nema_index -1 $BASE.1.fq -2 $BASE.2.fq \
          -o $BASE.quant --libType IU;
```

to 

```
salmon quant -i nema_index --libType IU -1 $BASE.1.fq -2 $BASE.2.fq \
          -o $BASE.quant;
```

the operative change is moving the library type to come _before_ the input fasta/q files.  This is a quirk of the way Salmon parses and interprets the read input, and is something I will add to / address in the documentation today.  The command you have currently will work, but it will always apply the default (paired-end) library type to the library being quantified.  In this case, the default (`IU`) just happens to match!

--Rob

**Comment by ctb** [comment]
Ahh, thanks -- will update.
